"""ASS 字幕生成工具。

提供三个生成函数：
- _segments_to_ass(segments)              ：VAD 级 ASS（有 words 时生成卡拉OK逐字高亮，
                                              无 words 时与 SRT 行划分一致）
- _timestamps_to_ass_karaoke(ts_list, offset_ms)：字级卡拉OK ASS 逐字高亮 \\kf 标签

支持 Segment dataclass 和 dict 两种输入格式。
"""

from __future__ import annotations

from typing import Any


def _format_ass_time(ms):
    """毫秒 → ASS 时间格式 h:mm:ss.cc（厘秒）"""
    total_cs = int(ms / 10)
    cs = total_cs % 100
    total_s = total_cs // 100
    s = total_s % 60
    total_m = total_s // 60
    h = total_m // 60
    m = total_m % 60
    return f"{h}:{m:02}:{s:02}.{cs:02}"


def _get_seg_field(seg: Any, key: str, default=None):
    """从 dict 或 dataclass 中安全获取字段。"""
    if isinstance(seg, dict):
        return seg.get(key, default)
    return getattr(seg, key, default)


def _get_words(seg: Any):
    """从 segment 中提取 word 级时间戳列表。

    返回 [{"start": float(sec), "end": float(sec), "text": str}, ...]
    支持 WordTimestamp dataclass 和 dict 两种格式。
    """
    words = _get_seg_field(seg, "words", [])
    if not words:
        # 兼容旧的 _char_ts 字段
        words = _get_seg_field(seg, "_char_ts", [])
    if not words:
        return []

    result = []
    for w in words:
        if isinstance(w, dict):
            result.append(w)
        else:
            # WordTimestamp dataclass
            result.append({
                "start": w.start_ms / 1000.0,
                "end": w.end_ms / 1000.0,
                "text": w.text,
            })
    return result


ASS_HEADER = """[Script Info]
; Generated by funclip-pro Qwen3-ASR
Title: Subtitles
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,48,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,1,2,10,10,30,1
Style: Karaoke,微软雅黑,56,&H00FFFFFF,&H0000D4FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,10,10,50,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _segments_to_ass(segments):
    """将 segments 转换为 ASS 字幕。

    对每个 segment：
    - 如果有 word 级时间戳（words 字段），生成卡拉 OK 逐字高亮（Karaoke 样式）
    - 如果没有 word 级时间戳，生成普通字幕行（Default 样式）

    支持 Segment dataclass 和 dict 两种输入。

    Args:
        segments: List[Union[Segment, dict]]
                  每个元素须包含 start_ms/start, end_ms/end, text 字段；
                  可选 words（WordTimestamp 列表）或 _char_ts 字段。

    Returns:
        str: 完整 ASS 文件内容
    """
    events = []
    for seg in segments:
        if isinstance(seg, dict):
            start_ms = int(seg["start"])
            end_ms = int(seg["end"])
            text = seg.get("text", "").strip()
        else:
            start_ms = seg.start_ms
            end_ms = seg.end_ms
            text = seg.text.strip()

        if not text:
            continue
        start_str = _format_ass_time(start_ms)
        end_str = _format_ass_time(end_ms)

        # 尝试获取 word 级时间戳
        words = _get_words(seg)
        if words and len(words) > 1:
            smoothed = _smooth_timestamps(words)
            karaoke_text = ""
            prev_end_sec = smoothed[0]["start"]
            for token in smoothed:
                gap_sec = token["start"] - prev_end_sec
                if gap_sec > 0.05:
                    gap_cs = int(gap_sec * 100)
                    karaoke_text += f"{{\\k{gap_cs}}}"
                dur_sec = token["end"] - token["start"]
                dur_cs = max(int(dur_sec * 100), 1)
                karaoke_text += f"{{\\kf{dur_cs}}}{token['text']}"
                prev_end_sec = token["end"]
            events.append(
                f"Dialogue: 1,{start_str},{end_str},Karaoke,,0,0,0,,{karaoke_text}"
            )

    return ASS_HEADER + "\n".join(events)


def _smooth_timestamps(tokens):
    """平滑过短的字级时间戳（<50ms 的借用后续空隙补足）。"""
    if not tokens:
        return []
    smoothed = [dict(t) for t in tokens]
    for i in range(len(smoothed)):
        curr = smoothed[i]
        dur = curr["end"] - curr["start"]
        if dur < 0.05 and i < len(smoothed) - 1:
            next_t = smoothed[i + 1]
            gap = next_t["start"] - curr["end"]
            if gap > 0.05:
                borrow = min(gap * 0.8, 0.2)
                curr["end"] += borrow
    return smoothed


def _timestamps_to_ass_karaoke(ts_list, offset_ms=0, max_chars=25, max_gap=1.0):
    """将 Qwen 字级时间戳转换为卡拉OK ASS 字幕。

    复用 _split_timestamps_to_segments 的分句逻辑，
    然后在每行内部插入 \\kf{持续时间} 标签实现逐字高亮。

    Args:
        ts_list: List[{"start": sec, "end": sec, "text": str}]
        offset_ms: 该 VAD 段在整个音频中的偏移毫秒

    Returns:
        str: 完整的 ASS 文件内容（带 Header）
    """
    if not ts_list:
        return ""

    # 收集完整的 sentence text（拼接所有 token 文本）
    sentence_text = "".join(ts.get("text", "") for ts in ts_list)

    # 复用智能分句函数
    from funclip_pro.core.asr import _split_timestamps_to_segments
    segments = _split_timestamps_to_segments(ts_list, sentence_text, offset_ms)

    if not segments:
        return ""

    events = []

    for seg in segments:
        char_ts = seg.get("_char_ts", [])
        if not char_ts or len(char_ts) < 1:
            continue

        smoothed = _smooth_timestamps(char_ts)
        start_str = _format_ass_time(seg["start"])
        end_str = _format_ass_time(seg["end"])

        karaoke_text = ""
        prev_end_sec = smoothed[0]["start"]
        for token in smoothed:
            # 等待时间 \k（与前一词的间隙）
            gap_sec = token["start"] - prev_end_sec
            if gap_sec > 0.05:
                gap_cs = int(gap_sec * 100)
                karaoke_text += f"{{\\k{gap_cs}}}"
            # 持续时间 \kf
            dur_sec = token["end"] - token["start"]
            dur_cs = max(int(dur_sec * 100), 1)
            karaoke_text += f"{{\\kf{dur_cs}}}{token['text']}"
            prev_end_sec = token["end"]

        events.append(
            f"Dialogue: 0,{start_str},{end_str},Karaoke,,0,0,0,,{karaoke_text}"
        )

    return ASS_HEADER + "\n".join(events)
